/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package utils;

import javax.swing.ImageIcon;

/**
 *
 * @author Sophie
 */
public class Tuto1 extends javax.swing.JDialog {

    private int position;

    /**
     * Creates new form Tuto1
     */
    public Tuto1() {

        initComponents();
        setLocationRelativeTo(null);

        setTitle("Como buscar la ruta del archivo txt");
        position = 1;
        changeResources(position);
        tuto2_img.setVisible(false);
        tuto5_img.setVisible(false);
        tuto6_img.setVisible(false);
        tuto7_img.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tuto1_img = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        tuto2_img = new javax.swing.JLabel();
        next = new javax.swing.JButton();
        tuto5_img = new javax.swing.JLabel();
        tuto6_img = new javax.swing.JLabel();
        tuto7_img = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        tuto1_img1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt.setFont(new java.awt.Font("Microsoft Tai Le", 0, 18)); // NOI18N
        txt.setText(" Primer paso: Ubicar el archivo de texto que se va a anexar.");
        getContentPane().add(txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 750, 30));

        jLabel2.setBackground(new java.awt.Color(51, 153, 255));
        jLabel2.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo-blanco.jpg"))); // NOI18N
        jLabel2.setText(" Primer paso: Ubicar el archivo de texto que se va a anexar.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 60));

        tuto1_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/play.png"))); // NOI18N
        getContentPane().add(tuto1_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 70, 70));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cursor2.png"))); // NOI18N
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 400, 50, 40));

        tuto2_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/play.png"))); // NOI18N
        tuto2_img.setText("jLabel1");
        getContentPane().add(tuto2_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 60, -1));

        next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cursor.png"))); // NOI18N
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        getContentPane().add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 400, 50, 40));

        tuto5_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/play.png"))); // NOI18N
        getContentPane().add(tuto5_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 60, 60));

        tuto6_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/play.png"))); // NOI18N
        tuto6_img.setText("jLabel1");
        getContentPane().add(tuto6_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 60, 60));

        tuto7_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/play.png"))); // NOI18N
        getContentPane().add(tuto7_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 70, 70));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tuto1.PNG"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 770, 420));

        tuto1_img1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/play.png"))); // NOI18N
        getContentPane().add(tuto1_img1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 70, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        position++;
        changeResources(position);


    }//GEN-LAST:event_nextActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        position--;
        changeResources(position);
    }//GEN-LAST:event_backActionPerformed

    void changeResources(int pos) {
        switch (position) {
            case 1:
                txt.setText(" Primer paso: Ubicar el archivo de texto que se va a anexar.");
                back.setVisible(false);
                tuto1_img.setVisible(true);
                background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tuto1.PNG")));
                break;
            case 2:
                back.setVisible(true);
                tuto1_img.setVisible(false);
                tuto2_img.setVisible(true);
                background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tuto2.PNG")));
                txt.setText(" Segundo paso: Entrar a la unidad 'EQUIPO'");
                break;
            case 3:
                txt.setText(" Tercer paso: Ubicar el archivo txt");
                tuto2_img.setVisible(false);
                background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tuto3.PNG")));
                break;
            case 4:
                txt.setText(" Cuarto paso: Si está guardada en una de las bibliotecas entrar a 'Usuarios'");
                tuto5_img.setVisible(false);
                background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tuto4.PNG")));
                break;
            case 5:
                txt.setText(" Quinto paso: Ubicamos el lugar donde está guardado el txt");
                tuto5_img.setVisible(true);
                background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tuto5.PNG")));
                tuto6_img.setVisible(false);
                break;
            case 6:
                txt.setText(" Sexto paso: Una forma es dar click derecho sobre la barra y la opción 'Copiar direccion' ");
                tuto6_img.setVisible(true);
                tuto5_img.setVisible(false);
                tuto7_img.setVisible(false);
                background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tuto6.PNG")));
                next.setVisible(true);
                break;
            case 7:
                txt.setText(" Septimo paso: Otra forma es dar click directo sobre la barra y copiar la ruta señalada ");
                next.setVisible(true);
                tuto7_img.setVisible(true);
                tuto6_img.setVisible(false);
                background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tuto7.PNG")));

                break;
            case 8:
                txt.setText(" Octavo paso: Pegar la ruta copia y anexar otro slash agregando el nombre del archivo con la extensión ");
                background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tuto8.PNG")));
                tuto7_img.setVisible(false);
                next.setVisible(false);
                break;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tuto1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tuto1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tuto1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tuto1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Tuto1 dialog = new Tuto1();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel background;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton next;
    private javax.swing.JLabel tuto1_img;
    private javax.swing.JLabel tuto1_img1;
    private javax.swing.JLabel tuto2_img;
    private javax.swing.JLabel tuto5_img;
    private javax.swing.JLabel tuto6_img;
    private javax.swing.JLabel tuto7_img;
    private javax.swing.JLabel txt;
    // End of variables declaration//GEN-END:variables
}
